<?php return [

    // Název jazyka (zobrazí se ve výběru jazyka)
    'lang_name'          => 'Čeština',

    // Navigace
    'nav_overview'       => 'Přehled',
    'nav_management'     => 'Správa',
    'nav_dashboard'      => 'Dashboard',
    'nav_firmware'       => 'Firmware',
    'nav_docs'           => 'Dokumentace',
    'nav_devices'        => 'Zařízení',
    'nav_users'          => 'Uživatelé',
    'nav_logout'         => 'Odhlásit se',

    // Obecné
    'btn_cancel'         => 'Zrušit',
    'btn_confirm'        => 'Potvrdit',
    'btn_add'            => 'Přidat',
    'btn_save'           => 'Uložit',
    'btn_upload'         => 'Nahrát',
    'btn_delete'         => 'Smazat',
    'btn_management'     => 'Správa',
    'modal_device_label' => 'Název zařízení',
    'label_notes'        => 'Poznámky (volitelné)',
    'label_notes_ph'     => 'Krátký popis…',
    'label_name'         => 'Název',
    'label_slug'         => 'Slug (URL identifikátor)',
    'label_slug_hint'    => 'Malá písmena, čísla a pomlčky',
    'label_category'     => 'Kategorie',
    'label_file'         => 'Soubor',
    'label_size'         => 'Velikost',
    'label_uploaded'     => 'Nahráno',
    'label_version'      => 'Verze',
    'label_status'       => 'Stav',
    'label_group'        => 'Skupina',
    'label_type'         => 'Typ',
    'label_component'    => 'Komponenta',
    'label_hw_version'   => 'HW verze',
    'label_fw_current'   => 'FW nyní',
    'label_fw_latest'    => 'Poslední FW',
    'label_uptime'       => 'Uptime',
    'label_last_seen'    => 'Poslední kontakt',
    'label_last_seen_short' => 'Online',
    'label_registered'   => 'Registrováno',
    'label_role'         => 'Role',
    'label_username'     => 'Uživatelské jméno',
    'label_full_name'    => 'Celé jméno',
    'label_mac'          => 'MAC',
    'label_label'        => 'Název',
    'label_ip'           => 'IP',
    'label_time'         => 'Čas',
    'label_event'        => 'Událost',
    'label_fw_version_col' => 'FW verze',

    // Stavové odznaky
    'status_ok'          => 'Aktuální',
    'status_update'      => 'Dostupná aktualizace',
    'status_installing'  => 'Instaluje se',
    'status_offline'     => 'Offline',
    'status_never'       => 'Nikdy neviděno',
    'status_online'      => 'Online',

    // Dashboard – statistiky
    'stat_total'         => 'Celkem',
    'stat_online'        => 'Online / OK',
    'stat_offline'       => 'Offline',
    'stat_update'        => 'Čeká aktualizaci',
    'stat_installing'    => 'Instaluje se',

    // Dashboard
    'dash_title'         => 'Dashboard',
    'dash_no_devices'    => 'Žádná zařízení se zatím nepřipojila.',
    'dash_no_devices_hint' => 'Zařízení se zaregistrují automaticky při prvním OTA volání.',
    'dash_col_fw_current'   => 'Aktuální FW',
    'dash_col_fw_available' => 'Dostupný FW',
    'dash_col_group_type_comp' => 'Skupina / Typ / Komponenta',

    // Firmware stránka
    'fw_title'           => 'Firmware',
    'fw_groups'          => 'Skupiny',
    'fw_no_groups'       => 'Zatím žádné skupiny',
    'fw_device_types'    => 'Typy zařízení',
    'fw_no_types'        => 'Žádné typy',
    'fw_components'      => 'Komponenty',
    'fw_no_components'   => 'Žádné komponenty',
    'fw_hw_versions'     => 'HW verze',
    'fw_no_hw'           => 'Žádné HW verze',
    'fw_select_hint'     => 'Vlevo vyberte skupinu → typ → komponentu → HW verzi',
    'fw_tab_firmware'    => 'Firmware',
    'fw_tab_docs'        => 'Dokumentace',
    'fw_upload_title'    => 'Nahrát firmware',
    'fw_version_label'   => 'Verze firmware',
    'fw_version_format'  => 'Formát: <code>YY.M.PATCH</code> (např. %s)',
    'fw_notes_ph'        => 'Co se změnilo…',
    'fw_btn_upload'      => 'Nahrát firmware',
    'fw_history'         => 'Historie firmware',
    'fw_no_firmware'     => 'Zatím nebyl nahrán žádný firmware',
    'fw_dropzone_main'   => 'Přetáhni .bin soubor sem',
    'fw_dropzone_sub'    => 'nebo klikni pro výběr',

    // Modály – přidání / přejmenování
    'modal_rename_title' => 'Přejmenovat',
    'modal_rename_btn'   => 'Uložit',
    'modal_new_group'    => 'Nová skupina',
    'modal_new_type'     => 'Nový typ zařízení',
    'modal_new_comp'     => 'Nová komponenta',
    'modal_new_hw'       => 'Nová HW verze',
    'modal_slug_hw'      => 'Slug HW verze',
    'modal_slug_hint'    => 'Malá písmena, čísla a pomlčky',
    'modal_btn_add'      => 'Přidat',
    'modal_group_ph'     => 'Domácnost',
    'modal_type_ph'      => 'Řídicí jednotka',
    'modal_comp_ph'      => 'Hlavní deska',
    'modal_fullname_ph'  => 'Jan Novák',
    'badge_me'           => 'Já',
    'badge_latest'       => 'poslední',
    'role_admin'         => 'Správce',
    'role_viewer'        => 'Pozorovatel',

    // Potvrzení smazání
    'confirm_delete_group'  => 'Smazat skupinu %s?',
    'confirm_delete_type'   => 'Smazat typ %s?',
    'confirm_delete_comp'   => 'Smazat komponentu %s?',
    'confirm_delete_hw'     => 'Smazat HW verzi %s?',
    'confirm_delete_fw'     => 'Smazat firmware %s?',
    'confirm_delete_doc'    => 'Smazat dokument %s?',
    'confirm_delete_device' => 'Opravdu smazat zařízení %s? Zaregistruje se znovu při dalším OTA volání.',
    'confirm_reset_totp'    => 'Resetovat autentizátor uživatele %s? Uživatel bude muset provést nové párování.',
    'confirm_delete_user'   => 'Smazat uživatele %s?',
    'confirm_reset_own_totp' => 'Odpojit aktuální autentizátor a spárovat nový?',

    // Dokumenty
    'doc_upload_title'   => 'Nahrát dokument',
    'doc_list_title'     => 'Dokumenty',
    'doc_no_docs'        => 'Žádná dokumentace zatím nahrána',
    'doc_dropzone_main'  => 'Přetáhni soubor sem',
    'doc_dropzone_sub'   => 'PDF, PNG, JPG, ZIP, KiCad — nebo klikni pro výběr',
    'doc_file_hint'      => 'PDF, PNG, JPG, ZIP, KiCad — max 50 MB',
    'doc_cat_schema'     => 'Schéma zapojení',
    'doc_cat_pcb'        => 'PCB / Gerber',
    'doc_cat_platformio' => 'PlatformIO projekt',
    'doc_cat_photo'      => 'Fotka',
    'doc_cat_other'      => 'Ostatní',

    // Zařízení
    'dev_title'          => 'Zařízení',
    'dev_all'            => 'Všechna zařízení',
    'dev_back'           => 'Zpět na seznam',
    'dev_info'           => 'Info',
    'dev_monitoring'          => 'Nastavení monitoringu',
    'dev_interval'            => 'Interval hlášení (s)',
    'dev_tolerance'           => 'Tolerance (s)',
    'dev_monitoring_disabled' => 'Nikdy neoznačovat jako offline',
    'dev_update_policy'       => 'Aktualizace firmware',
    'dev_updates_disabled'    => 'Zakázat aktualizace',
    'dev_allow_downgrade'     => 'Povolit downgrade na starší verzi',
    'filter_all_groups'       => 'Všechny skupiny',
    'filter_all_types'        => 'Všechny typy',
    'dev_danger_zone'    => 'Nebezpečná zóna',
    'dev_delete'         => 'Smazat zařízení',
    'dev_install_docs'   => 'Dokumentace instalace',
    'dev_no_install_docs' => 'Žádná dokumentace instalace',
    'dev_events'         => 'Historie událostí',
    'dev_no_events'      => 'Žádné záznamy',
    'dev_upload_doc'     => 'Nahrát dokumentaci instalace',
    'dev_doc_cat_photo'  => 'Fotka instalace',
    'dev_col_name'       => 'Název',
    'dev_col_fw'         => 'FW',
    'dev_col_last_seen'  => 'Poslední kontakt',
    'dev_no_devices'     => 'Žádná zařízení se zatím nepřipojila.',
    'dev_no_devices_hint' => 'Zařízení se zaregistrují automaticky při prvním OTA volání.',

    // Typy událostí
    'event_checkin'      => 'Hlášení',
    'event_download'     => 'Stahování FW',
    'event_fw_changed'   => 'FW aktualizován',

    // Účet
    'acc_title'          => 'Můj účet',
    'acc_info'           => 'Informace o účtu',
    'acc_totp'           => 'Autentizátor',
    'acc_totp_desc'      => 'Resetování odpojí aktuální autentizátor a okamžitě tě přesměruje na nové párování. Ujisti se, že máš k dispozici záložní kódy nebo přístup ke starému autentizátoru.',
    'acc_totp_reset'     => 'Resetovat párování autentizátoru',

    // Uživatelé
    'usr_title'          => 'Uživatelé',
    'usr_add'            => 'Přidat uživatele',
    'usr_col_user'       => 'Uživatel',
    'usr_col_fullname'   => 'Celé jméno',
    'usr_col_role'       => 'Role',
    'usr_col_totp'       => 'Autentizátor',
    'usr_col_created'    => 'Registrován',
    'usr_totp_paired'    => 'Spárováno',
    'usr_totp_unpaired'  => 'Nespárováno',
    'usr_edit_title'     => 'Upravit uživatele',
    'usr_new_title'      => 'Nový uživatel',
    'usr_role_viewer'    => 'Pozorovatel – pouze přehled',
    'usr_role_admin'     => 'Správce – plný přístup',
    'usr_slug_hint'      => 'Malá písmena, čísla a pomlčky. Uživatel si spáruje autentizátor při prvním přihlášení.',

    // Přihlášení
    'login_title'        => 'Přihlášení',
    'login_subtitle'     => 'Přihlaste se pomocí autentizátoru',
    'login_username'     => 'Uživatelské jméno',
    'login_continue'     => 'Pokračovat',
    'login_signing_as'   => 'Přihlášení jako',
    'login_change_user'  => 'Změnit uživatele',
    'login_tab_totp'     => 'Autentizátor',
    'login_tab_backup'   => 'Záložní kód',
    'login_totp_label'   => '6místný kód z aplikace',
    'login_btn_signin'   => 'Přihlásit se',
    'login_backup_label' => 'Záložní kód',
    'login_backup_hint'  => 'Po použití se kód smaže.',
    'login_btn_backup'   => 'Přihlásit záložním kódem',
    'login_err_not_found'    => 'Uživatel nenalezen.',
    'login_err_wrong_backup' => 'Nesprávný záložní kód.',
    'login_err_wrong_code'   => 'Nesprávný kód.',
    'login_err_rate_limit'   => 'Příliš mnoho neúspěšných pokusů. Zkuste to znovu za 15 minut.',

    // Nastavení (první spuštění)
    'setup_title'        => 'Nastavení',
    'setup_subtitle'     => 'První spuštění – spárování autentizátoru',
    'setup_backup_title' => 'Ulož si záložní kódy!',
    'setup_backup_body'  => 'Každý kód lze použít jednou při ztrátě přístupu. Po zavření je znovu neuvidíš.',
    'setup_backup_done'  => 'Kódy jsem si uložil, jít do aplikace',
    'setup_step1'        => 'Otevři <strong>Google Authenticator</strong> (nebo Aegis, Authy…)',
    'setup_step2'        => 'Klepni na <strong>+</strong> → <strong>Naskenovat QR kód</strong>',
    'setup_step3'        => 'Nebo zadej klíč ručně přes <strong>Zadat kód ručně</strong>',
    'setup_secret_label' => 'Tajný klíč (ruční zadání)',
    'setup_code_label'   => 'Ověřovací kód z aplikace',
    'setup_btn_verify'   => 'Ověřit a dokončit nastavení',
    'setup_err_code'     => 'Kód nesedí. Zkontroluj čas na telefonu a zkus znovu.',

    // Barevný režim
    'theme_light'        => 'Světlý',
    'theme_dark'         => 'Tmavý',
    'theme_auto'         => 'Automaticky',
    'theme_label'        => 'Motiv',

    // JS řetězce (window.Lang)
    'js_added'           => 'Přidáno',
    'js_saved'           => 'Uloženo',
    'js_renamed'         => 'Přejmenováno',
    'js_deleted'         => 'Smazáno',
    'js_uploading'       => 'Nahrávám…',
    'js_doc_uploaded'    => 'Dokument nahrán',
    'js_fw_uploaded'     => 'Firmware %s nahrán',
    'js_upload_error'    => 'Chyba při nahrávání',
    'js_network_error'   => 'Chyba sítě',
    'js_user_added'      => 'Uživatel přidán',
    'js_totp_reset'      => 'TOTP resetováno',
    'js_settings_saved'  => 'Nastavení uloženo',
    'js_error'           => 'Chyba',
    'js_must_be_bin'     => 'Soubor musí být .bin',
    'js_reset'           => 'Resetovat',

    // Chyby AJAX endpointů
    'err_access_denied'      => 'Přístup odepřen',
    'err_invalid_csrf'       => 'Neplatný CSRF token',
    'err_invalid_data'       => 'Neplatné údaje',
    'err_no_file'            => 'Soubor nebyl nahrán nebo nastala chyba',
    'err_unsupported_ext'    => 'Nepodporovaný typ souboru. Povoleno: %s',
    'err_file_too_large'     => 'Soubor je větší než %s MB',
    'err_file_empty'         => 'Soubor je prázdný',
    'err_file_too_small'     => 'Soubor je příliš malý',
    'err_cannot_create_dir'  => 'Nelze vytvořit adresář',
    'err_cannot_save_file'   => 'Nelze uložit soubor na disk',
    'err_db_error'           => 'Chyba databáze',
    'err_invalid_version'    => 'Neplatný formát verze (očekáváno YY.M.PATCH, např. %s)',
    'err_invalid_slug'       => 'Neplatný slug: %s',
    'err_invalid_hw_version' => 'Neplatná HW verze',
    'err_user_exists'        => 'Uživatel již existuje',
    'err_unknown_action'     => 'Neznámá akce',
    'err_admin_required'     => 'Vyžadován administrátor',
    'err_invalid_entity'     => 'Neplatný typ entity',
    'err_invalid_hw_params'  => 'Neplatné parametry HW verze',
    'err_invalid_device'     => 'Neplatný identifikátor zařízení',
    'err_not_found'          => 'Záznam nenalezen',
    'err_file_missing'       => 'Soubor nenalezen na disku',
    'err_missing_id'         => 'Chybí ID',
];
