<?php return [

    // Language name (shown in the language picker)
    'lang_name'          => 'English',

    // Navigation
    'nav_overview'       => 'Overview',
    'nav_management'     => 'Management',
    'nav_dashboard'      => 'Dashboard',
    'nav_firmware'       => 'Firmware',
    'nav_docs'           => 'Documentation',
    'nav_devices'        => 'Devices',
    'nav_users'          => 'Users',
    'nav_logout'         => 'Log out',

    // Common
    'btn_cancel'         => 'Cancel',
    'btn_confirm'        => 'Confirm',
    'btn_add'            => 'Add',
    'btn_save'           => 'Save',
    'btn_upload'         => 'Upload',
    'btn_delete'         => 'Delete',
    'btn_management'     => 'Manage',
    'modal_device_label' => 'Device label',
    'label_notes'        => 'Notes (optional)',
    'label_notes_ph'     => 'Short description…',
    'label_name'         => 'Name',
    'label_slug'         => 'Slug (URL identifier)',
    'label_slug_hint'    => 'Lowercase letters, numbers and dashes',
    'label_category'     => 'Category',
    'label_file'         => 'File',
    'label_size'         => 'Size',
    'label_uploaded'     => 'Uploaded',
    'label_version'      => 'Version',
    'label_status'       => 'Status',
    'label_group'        => 'Group',
    'label_type'         => 'Type',
    'label_component'    => 'Component',
    'label_hw_version'   => 'HW version',
    'label_fw_current'   => 'Current FW',
    'label_fw_latest'    => 'Latest FW',
    'label_uptime'       => 'Uptime',
    'label_last_seen'    => 'Last seen',
    'label_last_seen_short' => 'Online',
    'label_registered'   => 'Registered',
    'label_role'         => 'Role',
    'label_username'     => 'Username',
    'label_full_name'    => 'Full name',
    'label_mac'          => 'MAC',
    'label_label'        => 'Label',
    'label_ip'           => 'IP',
    'label_time'         => 'Time',
    'label_event'        => 'Event',
    'label_fw_version_col' => 'FW version',

    // Status badges
    'status_ok'          => 'Up to date',
    'status_update'      => 'Update available',
    'status_installing'  => 'Installing',
    'status_offline'     => 'Offline',
    'status_never'       => 'Never seen',
    'status_online'      => 'Online',

    // Dashboard – stat cards
    'stat_total'         => 'Total',
    'stat_online'        => 'Online / OK',
    'stat_offline'       => 'Offline',
    'stat_update'        => 'Awaiting update',
    'stat_installing'    => 'Installing',

    // Dashboard
    'dash_title'         => 'Dashboard',
    'dash_no_devices'    => 'No devices have connected yet.',
    'dash_no_devices_hint' => 'Devices register automatically on their first OTA call.',
    'dash_col_fw_current'   => 'Current FW',
    'dash_col_fw_available' => 'Available FW',
    'dash_col_group_type_comp' => 'Group / Type / Component',

    // Firmware page
    'fw_title'           => 'Firmware',
    'fw_groups'          => 'Groups',
    'fw_no_groups'       => 'No groups yet',
    'fw_device_types'    => 'Device types',
    'fw_no_types'        => 'No types',
    'fw_components'      => 'Components',
    'fw_no_components'   => 'No components',
    'fw_hw_versions'     => 'HW versions',
    'fw_no_hw'           => 'No HW versions',
    'fw_select_hint'     => 'Select group → type → component → HW version on the left',
    'fw_tab_firmware'    => 'Firmware',
    'fw_tab_docs'        => 'Documentation',
    'fw_upload_title'    => 'Upload firmware',
    'fw_version_label'   => 'Firmware version',
    'fw_version_format'  => 'Format: <code>YY.M.PATCH</code> (e.g. %s)',
    'fw_notes_ph'        => 'What changed…',
    'fw_btn_upload'      => 'Upload firmware',
    'fw_history'         => 'Firmware history',
    'fw_no_firmware'     => 'No firmware uploaded yet',
    'fw_dropzone_main'   => 'Drop .bin file here',
    'fw_dropzone_sub'    => 'or click to select',

    // Modals – add / rename
    'modal_rename_title' => 'Rename',
    'modal_rename_btn'   => 'Save',
    'modal_new_group'    => 'New group',
    'modal_new_type'     => 'New device type',
    'modal_new_comp'     => 'New component',
    'modal_new_hw'       => 'New HW version',
    'modal_slug_hw'      => 'HW version slug',
    'modal_slug_hint'    => 'Lowercase letters, numbers and dashes',
    'modal_btn_add'      => 'Add',
    'modal_group_ph'     => 'Household',
    'modal_type_ph'      => 'Control unit',
    'modal_comp_ph'      => 'Main board',
    'modal_fullname_ph'  => 'John Smith',
    'badge_me'           => 'Me',
    'badge_latest'       => 'latest',
    'role_admin'         => 'Admin',
    'role_viewer'        => 'Viewer',

    // Delete confirmations
    'confirm_delete_group'  => 'Delete group %s?',
    'confirm_delete_type'   => 'Delete type %s?',
    'confirm_delete_comp'   => 'Delete component %s?',
    'confirm_delete_hw'     => 'Delete HW version %s?',
    'confirm_delete_fw'     => 'Delete firmware %s?',
    'confirm_delete_doc'    => 'Delete document %s?',
    'confirm_delete_device' => 'Really delete device %s? It will re-register on its next OTA call.',
    'confirm_reset_totp'    => 'Reset authenticator for user %s? The user will need to pair a new one.',
    'confirm_delete_user'   => 'Delete user %s?',
    'confirm_reset_own_totp' => 'Disconnect current authenticator and pair a new one?',

    // Documents
    'doc_upload_title'   => 'Upload document',
    'doc_list_title'     => 'Documents',
    'doc_no_docs'        => 'No documentation uploaded yet',
    'doc_dropzone_main'  => 'Drop file here',
    'doc_dropzone_sub'   => 'PDF, PNG, JPG, ZIP, KiCad — or click to select',
    'doc_file_hint'      => 'PDF, PNG, JPG, ZIP, KiCad — max 50 MB',
    'doc_cat_schema'     => 'Wiring diagram',
    'doc_cat_pcb'        => 'PCB / Gerber',
    'doc_cat_platformio' => 'PlatformIO project',
    'doc_cat_photo'      => 'Photo',
    'doc_cat_other'      => 'Other',

    // Devices
    'dev_title'          => 'Devices',
    'dev_all'            => 'All devices',
    'dev_back'           => 'Back to list',
    'dev_info'           => 'Info',
    'dev_monitoring'          => 'Monitoring settings',
    'dev_interval'            => 'Report interval (s)',
    'dev_tolerance'           => 'Tolerance (s)',
    'dev_monitoring_disabled' => 'Never mark as offline',
    'filter_all_groups'       => 'All groups',
    'filter_all_types'        => 'All types',
    'dev_danger_zone'    => 'Danger zone',
    'dev_delete'         => 'Delete device',
    'dev_install_docs'   => 'Installation documentation',
    'dev_no_install_docs' => 'No installation documentation',
    'dev_events'         => 'Event history',
    'dev_no_events'      => 'No records',
    'dev_upload_doc'     => 'Upload installation documentation',
    'dev_doc_cat_photo'  => 'Installation photo',
    'dev_col_name'       => 'Name',
    'dev_col_fw'         => 'FW',
    'dev_col_last_seen'  => 'Last seen',
    'dev_no_devices'     => 'No devices have connected yet.',
    'dev_no_devices_hint' => 'Devices register automatically on their first OTA call.',

    // Event types
    'event_checkin'      => 'Check-in',
    'event_download'     => 'FW download',
    'event_fw_changed'   => 'FW updated',

    // Account
    'acc_title'          => 'My account',
    'acc_info'           => 'Account information',
    'acc_totp'           => 'Authenticator',
    'acc_totp_desc'      => 'Resetting will disconnect the current authenticator and immediately redirect you to pair a new one. Make sure you have your backup codes or access to the old authenticator.',
    'acc_totp_reset'     => 'Reset authenticator pairing',

    // Users
    'usr_title'          => 'Users',
    'usr_add'            => 'Add user',
    'usr_col_user'       => 'User',
    'usr_col_fullname'   => 'Full name',
    'usr_col_role'       => 'Role',
    'usr_col_totp'       => 'Authenticator',
    'usr_col_created'    => 'Registered',
    'usr_totp_paired'    => 'Paired',
    'usr_totp_unpaired'  => 'Not paired',
    'usr_edit_title'     => 'Edit user',
    'usr_new_title'      => 'New user',
    'usr_role_viewer'    => 'Viewer – view only',
    'usr_role_admin'     => 'Admin – full access',
    'usr_slug_hint'      => 'Lowercase letters, numbers and dashes. The user will pair their authenticator on first login.',

    // Login
    'login_title'        => 'Login',
    'login_subtitle'     => 'Sign in with your authenticator',
    'login_username'     => 'Username',
    'login_continue'     => 'Continue',
    'login_signing_as'   => 'Signing in as',
    'login_change_user'  => 'Change user',
    'login_tab_totp'     => 'Authenticator',
    'login_tab_backup'   => 'Backup code',
    'login_totp_label'   => '6-digit code from app',
    'login_btn_signin'   => 'Sign in',
    'login_backup_label' => 'Backup code',
    'login_backup_hint'  => 'The code will be deleted after use.',
    'login_btn_backup'   => 'Sign in with backup code',
    'login_err_not_found'    => 'User not found.',
    'login_err_wrong_backup' => 'Incorrect backup code.',
    'login_err_wrong_code'   => 'Incorrect code.',
    'login_err_rate_limit'   => 'Too many failed attempts. Please try again in 15 minutes.',

    // Setup (first run)
    'setup_title'        => 'Setup',
    'setup_subtitle'     => 'First run – authenticator pairing',
    'setup_backup_title' => 'Save your backup codes!',
    'setup_backup_body'  => 'Each code can be used once if you lose access. You will not see them again after closing.',
    'setup_backup_done'  => 'I saved the codes, go to app',
    'setup_step1'        => 'Open <strong>Google Authenticator</strong> (or Aegis, Authy…)',
    'setup_step2'        => 'Tap <strong>+</strong> → <strong>Scan QR code</strong>',
    'setup_step3'        => 'Or enter the key manually via <strong>Enter setup key</strong>',
    'setup_secret_label' => 'Secret key (manual entry)',
    'setup_code_label'   => 'Verification code from app',
    'setup_btn_verify'   => 'Verify and complete setup',
    'setup_err_code'     => 'Code does not match. Check the time on your phone and try again.',

    // Color mode
    'theme_light'        => 'Light',
    'theme_dark'         => 'Dark',
    'theme_auto'         => 'Auto',
    'theme_label'        => 'Theme',

    // JS strings (window.Lang)
    'js_added'           => 'Added',
    'js_saved'           => 'Saved',
    'js_renamed'         => 'Renamed',
    'js_deleted'         => 'Deleted',
    'js_uploading'       => 'Uploading…',
    'js_doc_uploaded'    => 'Document uploaded',
    'js_fw_uploaded'     => 'Firmware %s uploaded',
    'js_upload_error'    => 'Upload error',
    'js_network_error'   => 'Network error',
    'js_user_added'      => 'User added',
    'js_totp_reset'      => 'TOTP reset',
    'js_settings_saved'  => 'Settings saved',
    'js_error'           => 'Error',
    'js_must_be_bin'     => 'File must be .bin',
    'js_reset'           => 'Reset',

    // AJAX error messages
    'err_access_denied'      => 'Access denied',
    'err_invalid_csrf'       => 'Invalid CSRF token',
    'err_invalid_data'       => 'Invalid data',
    'err_no_file'            => 'No file uploaded or an error occurred',
    'err_unsupported_ext'    => 'Unsupported file type. Allowed: %s',
    'err_file_too_large'     => 'File exceeds %s MB',
    'err_file_empty'         => 'File is empty',
    'err_file_too_small'     => 'File is too small',
    'err_cannot_create_dir'  => 'Cannot create directory',
    'err_cannot_save_file'   => 'Cannot save file to disk',
    'err_db_error'           => 'Database error',
    'err_invalid_version'    => 'Invalid version format (expected YY.M.PATCH, e.g. %s)',
    'err_invalid_slug'       => 'Invalid slug: %s',
    'err_invalid_hw_version' => 'Invalid HW version',
    'err_user_exists'        => 'User already exists',
    'err_unknown_action'     => 'Unknown action',
    'err_admin_required'     => 'Admin required',
    'err_invalid_entity'     => 'Invalid entity type',
    'err_invalid_hw_params'  => 'Invalid HW version parameters',
    'err_invalid_device'     => 'Invalid device identifier',
    'err_not_found'          => 'Record not found',
    'err_file_missing'       => 'File not found on disk',
    'err_missing_id'         => 'Missing ID',
];
